# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: crc0ti33x-capi-aws
  namespace: crc0ti33x
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: crc0ti33x-capi-aws
subjects:
- kind: ServiceAccount
  name: crc0ti33x-capi-aws
